google_project_id       = "fuchicorp-315502"
google_bucket_name      = "fuchi-bucket-01"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"